"use client"

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
// import logo from '@/image/logo.png'
import menu from '@/image/menu.png'
import person from '@/image/person.png'
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [open, setOpen] = useState(false)
  function toggleMenu(){
    setOpen((prev) => !prev);
  }
  const router = useRouter()
  function profilePage(){
    router.push("/profile")
  }


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

<header>
        <div className="w-full  z-10 fixed top-0 h-14 ">
            <div className="w-full h-14 items-center flex justify-between bg-zinc-950 shadow-blue-500 shadow-sm">
                <div className="text-3xl text-white px-5 font-semibold">
                    {/* <Image
                    src={logo} 
                    alt="logo"
                    className="ml-5 lg:w-52 w-32"
                    priority
                    /> */}
                    LOGO
                </div>
                <div className="hidden text-white lg:flex">
                  <ul className="flex gap-8">
                    <li className="hover:text-zinc-500">
                      <Link href="/">
                      Home
                      </Link>
                    </li>
                    <li className="hover:text-zinc-500">
                      <Link href="/login">
                      Login
                      </Link>
                    </li>
                    <li className="hover:text-zinc-500">
                    <Link href="/signup">
                      Signup
                      </Link>
                    </li>
                    <li onClick={toggleMenu} className="hover:text-zinc-500">
                    <Link href="/admin">
                      Admin
                      </Link>
                    </li>
                  </ul>
                </div>
                <div className="flex gap-3 mr-5 ">
                    <button onClick={profilePage}>
                    <Image
                    src={person} 
                    alt="user"
                    className="w-8"
                    priority 
                    />
                    </button>
                    <button onClick={toggleMenu} className="lg:hidden">
                        <Image
                        src={menu} 
                        alt="menu"
                        className="w-8"
                        priority 
                        />
                    </button>
                </div>
            </div>
        </div>
        <div className="top-16 flex lg:hidden text-black w-full h-14 fixed z-10">
            <div className={`h-12 flex ${open?"flex":"hidden"} items-center justify-center border-[1px] border-black shadow-sm shadow-black w-full bg-white`}>
            <ul className="flex gap-5">
                    <li onClick={toggleMenu} className="hover:text-zinc-500">
                      <Link href="/">
                      Home
                      </Link>
                    </li>
                    <li onClick={toggleMenu} className="hover:text-zinc-500">
                      <Link href="/login">
                      Login
                      </Link>
                    </li>
                    <li onClick={toggleMenu} className="hover:text-zinc-500">
                    <Link href="/signup">
                      Signup
                      </Link>
                    </li>
                    <li onClick={toggleMenu} className="hover:text-zinc-500">
                    <Link href="/admin">
                      Admin
                      </Link>
                    </li>
                  </ul>
            </div>       
        </div>
      </header>

        {children}
      </body>
    </html>
  );
}
